name: Master

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node-version }}-build-
            ${{ runner.OS }}-${{ matrix.node-version }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn lint

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node-version }}-build-
            ${{ runner.OS }}-${{ matrix.node-version }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn test

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-${{ matrix.node-version }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-${{ matrix.node-version }}-build-
            ${{ runner.OS }}-${{ matrix.node-version }}-
            ${{ runner.OS }}-

      - run: yarn install
      - run: yarn build
      - run: yarn size-limit

  depcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - run: npx depcheck

  commit-watch:
    runs-on: ubuntu-latest
    steps:
      - run: echo "fetch_depth=$((${{ github.event.pull_request.commits }} + 1))" >> $GITHUB_ENV

      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: ${{ env.fetch_depth }}

      - uses: actions/setup-node@v2
        with:
          node-version: 14.x

      - run: npx @eqworks/commit-watch -b ${{ github.event.pull_request.base.sha }} -h ${{ github.event.pull_request.head.sha }} -v
