name: Storybook Build & Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16.x
          cache: 'yarn'
          registry-url: https://npm.pkg.github.com/
          scope: "@eqworks"

      - run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.CD_GITHUB_TOKEN }}
      - name: Deploy
        run: yarn storybook-to-ghpages --ci
        env:
          GH_TOKEN: EQWorks:${{ secrets.CD_GITHUB_TOKEN }}
